name: Events Demo 1
on: 
  pull_request:
    # Specify activity types that trigger this workflow
    types: 
      - opened
    branches:
      - main
    # I need to add a colon nevertheless
  workflow_dispatch:
  push:
    # Only pushes to the main branch should trigger this workflow
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # Double asterisks would allow even further slashes 
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."